### ISSUE TITLE
如果配置的VS 路径不存在,就用默认的方式打开

### ISSUE THREAD

**Issue by wumiliu** [akof1314/VisualStudioFileOpenTool#1]
System.Diagnostics.Process devenv;
            if (!File.Exists(vsPath))//如果配置的VS 路径不存在,就用默认的方式打开
            {
                devenv = System.Diagnostics.Process.Start("explorer.exe", "/open," + solutionPath.ToString());
            }
            else
            {
                devenv = System.Diagnostics.Process.Start(vsPath, solutionPath);
            }

**Comment by akof1314** [comment]
路径不存在的话，可以通过调用层来判定。
